#!/usr/bin/env node
// Item 11: the README walkthrough runs as written, and the Codex installer renders
// agents without touching a real CODEX_HOME.
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { check, finish, group, ROOT, run, tempHome } from "./harness.mjs";
import { AGENTS, MARKER, checkAgents, installAgents, renderAgent } from "../install-cairn-codex.mjs";

group("README walkthrough");
check("every `cairn …` line in the walkthrough block runs and ends in a Brier score with n=1", "the README is the first thing a user runs; if it drifts from the CLI it teaches the wrong commands", () => {
  const readme = readFileSync(join(ROOT, "README.md"), "utf8");
  const section = readme.split("## Five-minute walkthrough")[1];
  const block = /```bash\n([\s\S]*?)```/.exec(section)[1];
  const commands = block.split("\n").filter((l) => l.startsWith("cairn "));
  assert.ok(commands.length >= 5, "walkthrough has commands");
  const home = tempHome();
  const now = "2026-09-22T12:00:00Z";
  const date = "2026-09-29";
  let id = null;
  const outputs = {};
  for (const line of commands) {
    const args = tokenize(line.replace("<date>", date).replace("<id>", id ?? "<id>")).slice(1);
    const r = run(args, { home, now });
    assert.equal(r.status, 0, `${line}\n${r.stderr}`);
    if (args[0] === "add") id = r.stdout.split(/\s+/)[0];
    outputs[args[0]] = r.stdout;
  }
  assert.match(id, /^p-20260922-[0-9a-z]{4}$/);
  assert.match(outputs.debt, /1 due this week/);
  assert.match(outputs.resolve, /Brier 0\.09 {2}process 0\.3333/);
  assert.match(outputs.score, /Brier overall {2}insufficient \(n=1\)/);
  assert.match(outputs.score, /resolved 1 · scored 1/);
  assert.doesNotMatch(outputs.score, /0\.090/);
  assert.ok(existsSync(outputs.export.trim()));
  assert.equal(readFileSync(outputs.export.trim(), "utf8").split("\n").filter(Boolean).length, 2);
});

group("Codex installer");
check("renders each agent with the marker, refuses to overwrite a foreign file, and --check logic agrees", "an installer that clobbers a user's own agent file is the one thing it must never do", () => {
  const dir = join(tempHome(), "agents");
  for (const name of AGENTS) {
    const toml = renderAgent(name);
    assert.ok(toml.startsWith(`${MARKER}\n`));
    assert.match(toml, new RegExp(`^name = "${name}"$`, "m"));
    assert.match(toml, /^sandbox_mode = "read-only"$/m);
    assert.match(toml, /Codex host boundary/);
  }
  assert.deepEqual(checkAgents(dir).length, AGENTS.length);
  installAgents(dir);
  assert.deepEqual(checkAgents(dir), []);
  installAgents(dir);
  writeFileSync(join(dir, `${AGENTS[0]}.toml`), "# a user's own agent\n");
  assert.throws(() => installAgents(dir), /was not generated by this installer/);
  assert.equal(readFileSync(join(dir, `${AGENTS[0]}.toml`), "utf8"), "# a user's own agent\n");
  assert.equal(checkAgents(dir).length, 1);
});
check("installer CLI: --help exits 0, unknown option exits 1, --check --agents-only against an empty CODEX_HOME exits 1", "the check must fail loudly when nothing is installed", () => {
  const spawn = (args, env) => { try { return { status: 0, out: execFileSync(process.execPath, [join(ROOT, "install-cairn-codex.mjs"), ...args], { encoding: "utf8", env: { ...process.env, ...env }, stdio: "pipe" }) }; } catch (e) { return { status: e.status, out: `${e.stdout}${e.stderr}` }; } };
  assert.equal(spawn(["--help"]).status, 0);
  assert.equal(spawn(["--bogus"]).status, 1);
  const empty = tempHome();
  assert.equal(spawn(["--check", "--agents-only"], { CODEX_HOME: empty }).status, 1);
  assert.equal(spawn(["--agents-only"], { CODEX_HOME: empty }).status, 0);
  assert.equal(spawn(["--check", "--agents-only"], { CODEX_HOME: empty }).status, 0);
});

function tokenize(line) {
  const out = [];
  const re = /"([^"]*)"|'([^']*)'|(\S+)/g;
  for (const m of line.matchAll(re)) out.push(m[1] ?? m[2] ?? m[3]);
  return out;
}

finish();
